### PR TITLE
updated Michael Rouille photo

### PR DESCRIPTION
**Pull request by glm-mrouille**
Hi, 

I updated my picture, but could not test the result locally.
Let me know if it is more convenient if I send it by email.

Cheers,

Michaël

### CODE REVIEW

**Comment by speedingdeer** [comment]
Hi Michael,

Ny picture is very nice, but Petra will have to reduce the size to align to the others. If you don't mine I will take this picture from here and make it available for Petra. She will publish it and I will close this PR. Does it sound good to you?

PS If you want to test something locally and you have some problems to run grunt server, you can always send me a direct message. I'm always available for help.

**Comment by glm-mrouille** [comment]
Hi Filip,

I certainly don't mind you handling the picture, let me know if you want me
to send it to you by email or if you successfully grabbed it from my branch.

Cheers,

Michaël

On Mon, Feb 9, 2015 at 10:42 AM, Filip Wiśniewski <notifications@github.com>
wrote:

> Hi Michael,
>
> Ny picture is very nice, but Petra will have to reduce the size to align
> to the others. If you don't mine I will take this picture from here and
> make it available for Petra. She will publish it and I will close this PR.
> Does it sound good to you?
>
> PS If you want to test something locally and you have some problems to run
> grunt server, you can always send me a direct message. I'm always available
> for help.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aigamedev/nucl.ai/pull/1#issuecomment-73480967>.
>



-- 


*DIRECT*  +33 (0)2 99 27 21 46
*MAIN *   +33 (0)2 99 27 21 40

michael.rouille@golaem.com
http://www.golaem.com

**Comment by speedingdeer** [comment]
We g

**Comment by speedingdeer** [comment]
I copied it already. Closing it then.
Thx!

**Pull request closed without merging**
